#!/usr/bin/env ruby

require 'brew_notify'

begin
  require 'slop'
rescue NameError, LoadError => e
  puts "Please run `bundle install` to update your system's gems, or run `gem install slop`"
  puts "Error message:\n #{e.message}"
end

opts = Slop.parse do |o|
  o.bool '-i', '--init', 'Copy launchagent to your ~/Library/LaunchAgents and initialize the notifier'
  o.string '-n', '--notifier', 'Specify the notifier to use. Must be one of gntp / growl / terminal_notifier '
  o.on '-v', '--version', 'print the version' do
    puts BrewNotify::VERSION
    exit
  end
end

puts opts.to_hash
