#!/usr/bin/env ruby

require "brew_notify"
require "thor"

class CLI < Thor
  include Thor::Actions

  desc "init", "Copies the plist to your ~/Library/LaunchAgents and symlinks the exe to /usr/local/bin"

  def init
    # `ln -s #{File.absolute_path(__FILE__)} /usr/local/bin`
    copy_file './lib/brew_notify/templates/com.github.brew_notify.plist',
      File.expand_path("~/Library/LaunchAgents/com.github.brew_notify.plist")
    create_link "/usr/local/bin/brew_notify", "exe/brew_notify"
  end

  desc "check", "debug_info"


  def self.source_root
    File.dirname(__FILE__)
  end

  self.source_paths << File.absolute_path(File.dirname(__FILE__) + "/../")

  def check
    self.source_paths.each do |f|
      puts File.absolute_path(f)
    end
    puts self.destination_root
  end
end

CLI.start
